---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld-demo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
